* Setting the stage [2025-02-03 Mon]

- Learn about SCP in general, SCP data analysis
- Understand SCP data structures
- Documentation
- scRNA-Seq vs SCP
- Shiny apps
- Quantitative data analysis
- SPC data modelling, identification uncertainty
- Cell types classifier/annotation
- Downstream analyses: trajectory analysis
- New visualisations
- Write paper! Or vignette.

** Hackathon plan  [2/7]

1. [X] Find a paper/dataset.
2. [X] Get the data.
3. [ ] Get the metadata.
4. [ ] Create a QFeatures object.
5. [ ] Process data.
6. [ ] Model SCP data with scplainer.
7. [ ] Apply trajectory analysis.

** Misc todos

- [ ] Identify important columns in the DIA-NN report file and those that
  we could drop to improve loading time.
- [ ] What precursor filtering do we want/need? What columns are
  needed?

** Where to find data

*** =scpdata=
=scpdata::scpdata()= returns a table of crurated datasets in the
=scpdata= package.

*** From papers
- What is the biological question? Does it match our usecase
  (modelling and trajectory analysis)?
- How many cells (check their PCA/t-SNE plot). Aim for > 1000 cells
  (depending on the biological question).
- What technology? Is is really MS-based (not ABseq, CITE-Seq).
- Do they share the data? Where?
- Do they document their data/files (metadata)?
- Do they share quantitative data (ideally at the PSM or peptide
  level)?

*** Two (three) candidates

- Deep single-cell proteomics quantifies low-abundant
  embryonictranscription factors and lineage markers during induced
  pluripotent stem cell differentiation [[https://www.ebi.ac.uk/pride/archive/projects/PXD054066][PXD054066]]
- Ai et al. Single Cell Proteomics Reveals Specific Cellular Subtypes
  in Cardiomyocytes Derived from Human iPSCs and Adult Hearts (2025)
  MCP. Data: [[https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=e576331ad1904dbbbcc7fe8456904854][MSV000094438]].
- Kreimer et al. [[https://pubs.acs.org/doi/10.1021/acs.analchem.3c00213][High-Throughput Single-Cell Proteomic Analysis of Organ-Derived
  Heterogeneous Cell Populations by Nanoflow Dual-Trap Single-Column
  Liquid Chromatography]] (2023) Analytical Chemistry. Data: MSV000094571.

* Working paper/data

Ai et al. (2025) [[https://www.sciencedirect.com/science/article/pii/S1535947625000088#sec6][Single Cell Proteomics Reveals Specific Cellular
Subtypes in Cardiomyocytes Derived from Human iPSCs and Adult Hearts]]

From the methods section:

** iPSC-derived human cardiomyocytes (iCMs)

*** iPSC culture and iCM differentiation

The 02iCTR human iPSC line was generated by the Cedars-Sinai Medical
Center iPSC Core from peripheral blood mononuclear cells of a healthy
male individual with nonintegrating oriP/EBNA1 plasmids, which allowed
for episomal expression of reprogramming factors and shown to be fully
pluripotent (13, 14). iPSCs were maintained in mTESR1 medium on
Matrigel-coated cell culture plates and passaged every 5 d at split
ratios from 1:6 to 1:12 as needed using Versene. Only iPSCs between
passage 17 and passage 35 were used for differentiation in this study
(13).

The iPSCs were differentiated into cardiomyocytes (iCMs) using an
established monolayer differentiation protocol utilizing small
molecule modulators of Wnt signaling (14). Differentiated iCMs were
metabolically purified by depriving cells of glucose, as previously
demonstrated (14). Purified iCMs expressed standard cardiac sarcomeric
markers cardiac troponin T (cTnT) and α-actinin.

*** iPSCs to iCMs isolation and sorting

At each timepoint, cells were dissociated with Accutase, collected and
resuspended in PBS+0.5 mM EDTA buffer. Cells were stained for
viability with Sytox Green dye (Thermo Scientific S7020, 1:5000) for
30 minutes on ice, washed in PBS+0.5mM EDTA buffer, and dispensed
using FACS-sorting machine (BD Biosciences) cell sorter, using a 100uM
nozzle and the “1.0-drop Single” sort setting with a 12/16 phase mask
into separate wells on a 384-well low binding PCR plate (Biorad
HSP3801) containing 200 nL of lysis buffer (100mM TEAB, 0.2% DDM,
10ng/nL trypsin) . Each experiment contained two rows of cells with 10
cells and 50 cells which were used as reference for library
preparation. Plates were covered with foil and stored at -80C for
further processing.

*** Loading the data

The code assumes that the data files reside in a =./data= directory in
the current working directory.

First quick check:

#+begin_src R
  library(tidyverse)
  acmsTab <- read_tsv("./data/aCMs_report.tsv.gz")

  library(scp)
  ## 299 cells
  acms <- readSCPfromDIANN(acmsTab)
  acms
#+end_src

** Adult cardiomyocytes (aCMs)

*** Human heart transportation and aCMs isolation and sorting

The hearts were screened by transthoracic echocardiogram, and only the
hearts with normal systolic function (ejection fraction > 40%) and
diastolic function (normal E/A ratio and E/e’ ratio) were included
(Table S2). Single cardiomyocytes were isolated from the chunks of the
left ventricular free wall (transported in University of Washington
solution) using enzymatic digestion isolation technique (in
calcium-free Tyrode solution with collagenase II [1.0 mg/ml,
Worthington Biochemical Corporation] and protease XXIV [0.1 mg/ml,
Sigma-Aldrich]) in a swirling flask for 60-90 minutes. Ventricular
single cells were prepared after filtration with 200 μm filter and
centrifugation to remove debris. Individual aCMs were dispensed into
separate wells on the same type of Bio-rad 384-well plate containing
same lysis buffer as for iCMs as the using a CellenONE (Cellenion) as
previously reported(15). To limit a potential bias during sample
preparation, all samples were provided a coded biospecimen name
throughout the entire process. During sample preparation and mass
spectrometry analysis, all personnel involved were blinded to the
human subject information and biospecimen coding except for one
scientist who carried out the plate mapping to ensure randomization of
samples but who was not involved in data acquisition. Once the data
acquisition and raw data file pre-processing using the coded
information was complete, one data analyst was provided the
de-identified information to proceed with the downstream
bioinformatics processing.

*** Loading the data

#+begin_src R
  library(tidyverse)
  icmsTab <- read_tsv("./data/iCMs.tsv.gz")

  library(scp)
  ## 2184 cells
  icms <- readSCPfromDIANN(icmsTab)
#+end_src

* Meta-data [2025-02-04 Tue]

Next stel is to parse the metadata needed for downstream data
modelling from the filenames.

#+begin_src R
  library(tidyverse)
  acmsTab <- read_tsv("./data/aCMs_report.tsv.gz")

  tab <- tibble(file = acmsTab[[1]]) |>
    mutate(file = sub("X.+CM_PROJECT\\\\", "", file))
  tab$date <- ymd(as.integer(substring(tab$file, 1, 6)))
#+end_src

What metadata is available in the filenames:
- Acquisition data (221019, ...)
- Subject number (Subject3, ...)
- Heart location (Lvendo, ...)
- Position in plate (A17, ...)
- ??? (BA18, ...)
