---
title: "Application of the scp pipeline on adult cardiomyocytes data"
author:
- name: Sven Berres
- name: Louise Buur
- name: Laurent Gatto
- name: Enrico Massignani
- name: Sam van Puyenbroeck
- name: Christophe Vanderaa
- name: Hannah Voß
package: QFeatures
abstract: >
 Application of the `scp` pipeline on adult cardiomyocytes data
 from Ai et al. 2025. This vignette is distributed under a CC BY-SA license.
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    code_folding: show
date: "`r BiocStyle::doc_date()`"
bibliography: scp.bib
vignette: >
  %\VignetteIndexEntry{Application of the scp pipeline on adult cardiomyocytes data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown()
```

# Introduction

# Data prepartion and processing

# Exploratory data analysis and quality control

# Statistical modelling

# Downstream analyses

# References {-}

# Session information

```{r si}
sessionInfo()
```